services:
  synchronous-app:
    container_name: synchronous-app
    image: synchronous-app:1.0.0
    pull_policy: never
    environment:
      THC_PATH: /actuator/health
      THC_PORT: 8010
      TZ: Europe/Prague
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/doc_submission_db
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      start_period: 8s
      timeout: 5s
      retries: 5
    ports:
      - "8010:8010"
    networks:
      - backend
