services:
  jms-app:
    container_name: jms-app
    build:
      context: ./jms-app
      dockerfile: Dockerfile
    environment:
      THC_PATH: /actuator/health
      THC_PORT: 8020
      TZ: Europe/Prague
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/doc_submission_db
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -T5 -qO- http://localhost:8080/actuator/health | grep UP || exit 1" ]
      start_period: 8s
      timeout: 5s
      retries: 5
    ports:
      - "8080:8080"
    networks:
      - backend
